version: "3.7"
services:
  app:
    environment:
      SHELL: /bin/sh
    build:
      context: .
      dockerfile: production.Dockerfile
      args:
        environment: development
        status: stable
    volumes:
      - .:/app
    ports:
      - 3000:3000
