default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fitune_challenge
  database: fitune_challenge
  username: davidst
  password: postgres

test:
  <<: *default
  database: fitune_challenge_test

production:
  <<: *default
  database: <%= Rails.application.credentials.prod_db_name %>
  username: <%= Rails.application.credentials.prod_db_user_name %>
  password: <%= Rails.application.credentials.prod_db_user_password %>
