default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: sqlite3
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/development-test.sqlite3

production:
  <<: *default
  database: db/development-test.sqlite3
