default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: sqlite3
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/development-test.sqlite3

production:
  <<: *default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Rails.application.credentials.prod_host_name %>
  database: <%= Rails.application.credentials.prod_db_name %>
  username: <%= Rails.application.credentials.prod_db_user_name %>
  password: <%= Rails.application.credentials.prod_db_user_password %>
